name: Update Dependencies
on:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:

jobs:
  update-dep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.sh
        uses: oven-sh/setup-bun@v1

      - name: Update dependencies
        run: |
          bunx npm-check-updates -u
          bun install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): bump dependencies"
          title: "chore(deps): bump dependencies"
          body: |
            This PR updates project dependencies.
            Please review and merge if everything looks good.
          branch: update-deps-${{ github.run_number }}
